### ISSUE TITLE
URI with undefined scheme

### ISSUE THREAD

**Issue by douzicao** [KurenaiRyu/im-sync-bot#14]
Login qq bot...
bot      | 2022-02-17 11:23:36.256  WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'telegramBot' defined in URL [jar:file:/workspace/bot.jar!/BOOT-INF/classes!/kurenai/imsyncbot/telegram/TelegramBot.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: URI with undefined scheme

**Comment by KurenaiRyu** [comment]
配置贴一下，日志如果还有更多的话也麻烦贴一下，另外`docker-compose.yaml`也最好贴一下，或是告诉我你用的是哪个镜像版本，我最近推上去的有nightly，test跟1.0.0。

注意如果涉及隐私记得打码

**Comment by douzicao** [comment]
配置文件和和docker都是按照你库得改得，自动拉的1.0.0版本，我现在又换回之前的版本了

**Comment by KurenaiRyu** [comment]
我更新了一下镜像，用`docker-compose pull bot && docker-compose up -d`更新一下应该就行了

**Comment by douzicao** [comment]
十分感谢
