### ISSUE TITLE
如何更新 Mirai 资源？

### ISSUE THREAD

**Issue by SliverRiver327** [KurenaiRyu/im-sync-bot#22]
Mirai 当前的最新版本为 2.15.0-RC (预览)
我需要使用这个版本驱动这个机器人，问问作者是怎么打包 mirai 资源的，以及如何更新

**Comment by KurenaiRyu** [comment]
暂时没对用户做这样的功能。如果你是之前就在用我推上去的docker镜像的话（也就是README里面那样跑），我可以晚点更新一下镜像；否则我最多上传一下编译好的文件了。

**Comment by SliverRiver327** [comment]
虽然不是之前就一直在跑，但是我需要用 mirai 的最新预览版本，不然我也登不上我的账号（

我有考虑过使用您的这个项目，也是因为上述原因最后抛弃掉了，也麻烦您更新一下资源

感激不尽

Best Regards,
Restent Ou
本邮件使用 Tutanota Mail 发送。



2023年6月24日 07:21 来自 ***@***.***:

**Comment by KurenaiRyu** [comment]
我个人是没成功用密码登录的，现在其实都是用的`ANDROID_WATCH`协议的二维码登录。只要删除掉密码就能够触发二维码登录了。

更新了1.2.2版本，我暂时只发布了编译后的文件，docker我环境有点麻烦暂时不推了。主要这边在弄一个新的版本所以旧版本不太想去动了，所以可能存在一些bug我没修的。

**Comment by SliverRiver327** [comment]
> 我个人是没成功用密码登录的，现在其实都是用的`ANDROID_WATCH`协议的二维码登录。只要删除掉密码就能够触发二维码登录了。
> 
> 更新了1.2.2版本，我暂时只发布了编译后的文件，docker我环境有点麻烦暂时不推了。主要这边在弄一个新的版本所以旧版本不太想去动了，所以可能存在一些bug我没修的。
> 
> Jar 包运行参考README。有问题可以继续问，我到时候参考写进README，往后我也希望只有一个jar包去运行。

Jar 包运行可以，我先试一下，谢谢

**Comment by SliverRiver327** [comment]
能用，但tx那边问题有点大，暂时不会修了
ANDROID_PAD 8.8.88 嗯是遭到了大规模风控
过几天再看看吧，谢谢作者
