### ISSUE TITLE
1.2.2 用户权限判断错误

### ISSUE THREAD

**Issue by lancer-wang** [KurenaiRyu/im-sync-bot#24]
![image](https://github.com/KurenaiRyu/im-sync-bot/assets/69783837/d329661f-1d0a-4298-9d5e-621b84be6a5c)

master-of-tg 我无论带不带双引号都不行
不知道是不是因为没有生成user.json

**Comment by lancer-wang** [comment]
用别的号就提示
![image](https://github.com/KurenaiRyu/im-sync-bot/assets/69783837/cd23b607-bbb4-4ea7-929f-575d334e36dc)

**Comment by lancer-wang** [comment]
Step 5/11 : COPY --chown=185 build/libs/lib/* /deployments/lib/
COPY failed: no source files were specified

本地构建docker的时候发现这个

**Comment by lancer-wang** [comment]
测试了半天,是最新版不会自动生成user.json
我切到1.2.0才有自动生成

**Comment by KurenaiRyu** [comment]
啊这，看起来bug多多。平时也就我知道的几个人在用没什么人反馈所以不知道问题，待会我看看吧

**Comment by KurenaiRyu** [comment]
试试 1.2.2.1 版本，自测应该是没问题了。
