### ISSUE TITLE
您好 偶然搜到您这个项目 ，这个可以实现转发消息tg消息给另一个tg账号吗？

### ISSUE THREAD

**Issue by corsgoo** [KurenaiRyu/im-sync-bot#25]
因为我目前有一个需求 ，我青龙面板的变量需要传递到tg上的一个机器人 。我搜了一下 有脚本可以实现青铜变量自动 推送到tg，但是他需要把推送的消息发送给另外一个机器人 。我希望可以实现这样的效果 不知道您这个是否可以稍加修改实现类似的功能

**Comment by KurenaiRyu** [comment]
这边没实现这样的功能，非常单纯的就是qq跟tg互转
